name: Prod Container App Build & Deploy

# When this action will be executed
on: 
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_run:
    workflows: ["Build Python application and Check Vulnerabilities"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:

defaults:
  run:
    working-directory: api

jobs:
  ACR-Import-to-PROD:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2

    - name: Push Image from Test ACR to PROD ACR
      uses: azure/CLI@v1
      with:
         inlineScript: |
	   az acr import --name fxpeupaccd02cr.azurecr.io --force --source fxteupaccd01cr.azurecr.io/fx-t-eu-paccd-01-ca:${{ github.sha }} --image fx-p-eu-paccd-02-ca:${{ github.sha }} --registry /subscriptions/{{ secrets.SUBSCRIPTION_ID }}/resourceGroups/fx-t-eu-paccd-01-rg/providers/Microsoft.ContainerRegistry/registries/fxteupaccd01cr.azurecr.io
