name: Prod Container App Build & Deploy

# When this action will be executed
on: 
  push:
    branches: [ "main" ]
  #pull_request:
    #branches: [ "main" ]
  workflow_run:
    workflows: ["Container App Build & Deploy in Test Environment"]
    branches: [main]
    types: 
      - completed
  workflow_dispatch:

defaults:
  run:
    working-directory: api

jobs:
  ACR-Import-to-PROD:
    runs-on: ubuntu-latest
    env:
      URI: ${{ secrets.URI }}
      KEY: ${{ secrets.KEY }}
      APPINSIGHTS_INSTRUMENTATIONKEY: ${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}
      
    steps:
    - name: Checkout to the branch
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to container registry
      uses: docker/login-action@v1
      with:
         registry: fxpeupaccd02cr.azurecr.io
         username: ${{ secrets.PROD_REGISTRY_USERNAME }}
         password: ${{ secrets.PROD_REGISTRY_PASSWORD }}
